--# insert into exercise_name values (4, 'PECS', 'asdasd', 1);
--insert into users (user_id, login, password,first_name, last_name, active, email)
--values (550, 'login_1', 'pass_1' , 'Vasyl', 'Vasylenko', 1, 'some1@mail.com');